# Generated by Django 4.1.5 on 2023-01-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Device_costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=128)),
                ('type_device', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=128)),
                ('delivery_date', models.DateField(null=True)),
            ],
        ),
    ]
